identifier: ch.lqvp.listenbrainz
name: ListenBrainz-Csutom
description: Plugin to submit listening data to ListenBrainz
author: lqvp
repo: https://github.com/lqvpcider-listenbrainz
entry:
  "plugin.js":
    type: main